name: Last Night On Earth (LNOE)
favicon: null
layout_spectrum: 0.71172
typography_spectrum: 0.8382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#777777'
    - '#000000'
    - '#c9c9c9'
    - '#272727'
    - '#565656'
  brandStrength: 0.375
  lightness: 0.4436886652838439
  saturation: 0.125
  rhythmicContrast: 0.7699055208358914
purpose: []
