name: Last Night On Earth (LNOE)
favicon: null
layout_spectrum: 0.03695198707282543
typography_spectrum: 0.22702969308011234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3515924154780805
  lightness: 0.4436886652838439
  saturation: 0.4591853024903685
  rhythmicContrast: 0.7699055208358914
purpose: []
